### ISSUE TITLE
Feature request: add shortcut to remove automatically added links from a block

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [sawhney17/logseq-automatic-linker#10]
Hi,

I think that when writing a multiline block, your addon can add many links that would be unwanted. If the user forgot to turn off the automatic linking feature beforehand, I think it can be be handy to have a way to remove the automatically generated shortcuts (or remove all of them) inside the current block.

Either by a shortcut or rather via right clicking on the block bullet.

Thanks for considering this!

**Comment by sawhney17** [comment]
I believe command z should work?
