### ISSUE TITLE
Feature request : support multi word links

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [sawhney17/logseq-automatic-linker#11]
Hi,

I think it would be very useful to support multi word links, for example when I type `I need to focus on my code projets` I would like to have a link created to my page `code projets`.

What do you think ? I know it would add a layer of complexity (especially wether to deal with imbricated links like [[code [[projets]]]])

If you do add this, I think it would be good to add a way to disable it in the settings because I can imagine some users wanting to use only single word links or something.

Have a nice day!

**Comment by sawhney17** [comment]
I believe this should already be available

**Comment by thiswillbeyourgithub** [comment]
Indeed it does! I seem to have a weird issue where it sometimes doesn't work. If I found a way to reproduce it I will open an issue.

Thanks!
