### ISSUE TITLE
Auto linker is not working with unicode

### ISSUE THREAD

**Issue by bluckholl** [sawhney17/logseq-automatic-linker#16]
Hi,
It seems auto linker is not working with Unicode  - I tested it with Hebrew - 
e.g. I have a page named יאיר and another page named Query
when I write line : יאיר and Query
Only Query is auto linked: יאיר and [[Query]]

Thanks for your great work :)
Asaf

**Comment by Slabhub** [comment]
any update for  this issue ?

**Comment by goldan** [comment]
I have the same issue, any plans to resolve it? That would be very helpful for multilingual graphs.

**Comment by yoono-toss** [comment]
I really need this..
