### ISSUE TITLE
Linker parsing property blocks

### ISSUE THREAD

**Issue by andremann** [sawhney17/logseq-automatic-linker#28]
Having the "autocomplete on Enter" on, the linker parses property blocks and tries to link them.
This corrupts the syntax and throws a parsing exception for the block.
E.g., `type:: page` becomes `[[type]]:: [[page]]`

**Comment by andreoliwa** [comment]
Hi, this should have been fixed by #29.
The new release made today includes the fix: https://github.com/sawhney17/logseq-automatic-linker/releases/tag/1.3.0
