### ISSUE TITLE
Plugin still supported?

### ISSUE THREAD

**Issue by neoromantic** [sawhney17/logseq-automatic-linker#55]
Just curious is this plugin still supported? I consider it is one of the most important features in my PKM-process and rely on it a lot. It's actually one of the reasons I prefer LogSeq to Obsidian.

If the author doesn't have time to support it - that's fine - I'd like to know would my PRs be reviewed&merged if I begin to support and develop it myself? 

Thanks!

**Comment by DutchPete** [comment]
@neoromantic you did not get a reply to your important question, unfortunately.

BTW, I was also on Obsidian and have more or less decided to switch to Logseq. Automatic Linker is an important plug-in for me too, but it is not the only reason for my switch.

Anyway, there is now a plug-in for Obsidian that does the same: [Freelinking](https://forum.obsidian.md/t/freelinking/440/42?u=klaas).

**Comment by sawhney17** [comment]
Hi, apologies for my extended leave from maintenance, i will be gradually easing into development in the coming days. PR's would definitely be appreciateed got quite the backlog.!
