### ISSUE TITLE
How are aliases handled?

### ISSUE THREAD

**Issue by DutchPete** [sawhney17/logseq-automatic-linker#60]
Let's say I have a page called Page-1 with an alias *pager*.
If I type `Page-1` anywhere, then as soon as I hit <kbd>enter</kbd>, then Page-1 get automatically converted into a wikilink `[[Page-1]]`.

I would have thought that if I type `pager` and hit <kbd>enter</kbd>, then pager would automatically gets converted into a wikilink `[[pager]]`. But it does not.

Sure enough, if I myself type `[[pager]]` it is a link that when clicked on takes me to the page called Page-1.

But I do not want to have to remember to type the square brackets myself; in fact, it requires me to remember all the aliases I have created, and that's not possible - I thought Automatic Linker does that for me.

So, what am I missing?

**Comment by adxsoft** [comment]
Great plugin. It would be a welcome addition if aliases were also included.

**Comment by adxsoft** [comment]
Aliases are catered for but the first time I put an alias on a page say **PageA** with an alias of _myfirstpage_ and then referred to the alias in my journal and used Cmd P to parse the line it did not pick it up **however** when I left the journal page and returned and tried it again it worked so it may be a caching issue. Othere than that glitch aliases are working fine

**Comment by DutchPete** [comment]
> aliases are working fine

So, what is wrong with the way I expect the plug-in to work as I describe above?

**Comment by adxsoft** [comment]
I tried your example in 9.15 and it works so don't understand your issue

**Comment by DutchPete** [comment]
I just reinstalled the plug-in, and this is what I get:

![image](https://github.com/sawhney17/logseq-automatic-linker/assets/10794265/78b42edd-d035-4cf9-9de4-4e6fa3cf3de2)

Every letter is transformed into a wikilink!
Someone opened an issue for this, so others have experienced this too.

**Comment by adxsoft** [comment]
I just installed the plugin and using 9.15 on Mac which seems to work. I
can't check it out on mobile as no plugin support.
Hopefully Sawney can get the problem sorted out.
Only thought I have is do a re-index which will rebuild any indexes and see
if that fixes it.
Success!

**Comment by DutchPete** [comment]
I don't Sawney is working on this anymore, seems like it has become abandonware.
I uninstalled it.

**Comment by adxsoft** [comment]
That's a shame .. let's hope he picks it up again. It's my favourite plugin

**Comment by DutchPete** [comment]
I agree it is a good plug-in, in principle. It was 1 of the 1<sup>st</sup> I installed when I started using Logseq. Alas ……

**Comment by adxsoft** [comment]
Btw .. what platform are you using?

**Comment by DutchPete** [comment]
macOS 13 Ventura.

**Comment by adxsoft** [comment]
I'm on Mac too so I'll see if I can recreate the weird output. If I can
recreate it I'll have a go at finding the bug 🙂

**Comment by DutchPete** [comment]
@adxsoft thanks. Have a look at issue #62.

**Comment by adxsoft** [comment]
Thanks, I'll check it out.

**Comment by adxsoft** [comment]
This was fixed.  I sent a fix to the author and he re issued the plugin
which I installed and works perfectly fine.

**Comment by DutchPete** [comment]
@adxsoft OK, thanks.
