### ISSUE TITLE
every letter gets parsed?

### ISSUE THREAD

**Issue by heemet** [sawhney17/logseq-automatic-linker#62]
Hi; I reinstalled this plugin because it didn't like the shortcuts i assigned. But even if I don't touch the settings at all it parses every letter of my block. I don't know if this is operator error. attaching a screen recording.

https://github.com/sawhney17/logseq-automatic-linker/assets/15643869/93e16d02-5dd7-4a20-9656-da40fd2cc57c

**Comment by davidefornelli** [comment]
I have the same issue.

**Comment by mruderman** [comment]
Me too; this is on the Linux appimage of LogSeq version 0.9.15
Unfortunately, the plugin appears unusable.

**Comment by DutchPete** [comment]
I have the same issue.

My worry is that this plug-in has become abandonware because Aryen does not seem to respond anymore.

**Comment by adxsoft** [comment]
If you have an alias somewhere in your graph that only has a space as the alias name then every space is assumed to be a link. 

`alias:: x`

where x is a SPACE!

The solution is find the 'bad' alias and either delete that line or put a actual alias name. 

Blank space is NOT an alias name. 

I will see if I can find the problem in the code .. it should ignore blank aliases.

**Comment by DutchPete** [comment]
I don't have aliases with spaces because properties cannot handle that, so if I want a multiword property I use hyphens, e.g. wordA-wordB.

**Comment by adxsoft** [comment]
An alias can have a space for it's value. Try it it gets accepted.

**Comment by DutchPete** [comment]
I don't want to try it because if I get used to it, sooner or later I will do it with another property too. Besides, it does bother me to use hyphens.

**Comment by adxsoft** [comment]
Ok, no problem.

**Comment by adxsoft** [comment]
Have submitted a Pull Request with the fix to resolve this issue

**Comment by mruderman** [comment]
@adxsoft, thanks for putting in the pull request.

Thank you @sawhney17 for developing this project, if you don't have time (totally understandable) for further maintenance of this extension, would you be OK if one of us officially forked it over, or would you be willing to open up admin rights for others (e.g., @adxsoft, myself, or others on this thread or in the broader community?

**Comment by andreoliwa** [comment]
> Have submitted a Pull Request with the fix to resolve this issue

- https://github.com/sawhney17/logseq-automatic-linker/pull/65

Maybe this issue can be closed.

**Comment by DutchPete** [comment]
@andreoliwa I installed the plug-in again and it works, so it is fixed therefore this issue can be closed, as you suggested.
Thanks for your help.

**Comment by andreoliwa** [comment]
@heemet or @sawhney17 have the power to close the issue. 😅
