### ISSUE TITLE
Will it work with logseq 0.10.3-alpha+nightly.20240112?

### ISSUE THREAD

**Issue by XesUl** [sawhney17/logseq-automatic-linker#71]
I have a problem. Everything I try doesn't work with the version in the title. I've already used the newest version, but it's still not working. Will there be a fix for auto linking? I heard that it works with version 0.8.3 or something like that, but I just want to use the current version for other plugins I use.

**Comment by rambalachandran** [comment]
Automatic Linker doesnt work for me either on 0.10.3. Tested with  AppImage in Ubuntu.

**Comment by XesUl** [comment]
> Automatic Linker doesnt work for me either on 0.10.3. Tested with AppImage in Ubuntu.

Ok good i thought its a problem only I have. Cause with a downgraded version it works but doesnt make sense to downgrade.

**Comment by clarkissac** [comment]
i fixed the issue with #77

**Comment by rambalachandran** [comment]
Thank you @clarkissac . But it appears the maintainer is not active for past few weeks. Hopefully he can get this merged in. Its a shame if this plugin gets broken as it is one of the important reasons I use logseq.
