### ISSUE TITLE
Can this be installed when offline?

### ISSUE THREAD

**Issue by egcolli** [sawhney17/logseq-automatic-linker#80]
Hi,
I'm in an environment that does not have direct access to the internet. Can this plugin be installed and work without internet access?
Thanks

**Comment by sawhney17** [comment]
Yes, this plugin can be installed offline without internet access. You must download the zip file from the releases section , turn on developer mode in Logseq and select "Load Unpacked Plugin" in the plugins page. 

Assuming you've unzipped the folder, you can just navigate to it from the file picker that appears in logseq when clicking load unpacked plugin and it should be good to go!
