### ISSUE TITLE
Feature request: Add the support to alias?

### ISSUE THREAD

**Issue by mzwlevi** [sawhney17/logseq-automatic-linker#9]
The automatic-linker is a wonderful plugin for logseq, do you have any plan to add the support to alias? 
<img width="394" alt="Screen Shot 2022-05-14 at 12 07 05" src="https://user-images.githubusercontent.com/78029539/168410151-071b3a35-667f-42e6-9fc0-5a7810cc6717.png">

Thank you!

**Comment by sawhney17** [comment]
What do you mean by this? How would it work? 

I can parse for the aliases created via `alias:: aliasName`

**Comment by jjaychen1e** [comment]
> What do you mean by this? How would it work?
> 
> I can parse for the aliases created via `alias:: aliasName`

For me, `alias:: aliasName` won't be linked automatically.
